// GENERATED by scripts/arc-precompute.mjs: the arc's annotation layout, solveAnnotations() in arc/annotate.ts. Do not edit by hand.
// Rerun with `npm run arc:precompute`; `npm run arc:check` verifies it matches a fresh solve.

import type { Annotation } from "./instrument";

export const ANNOTATIONS: Annotation[] = [
  {"id":"cut","track":"weight","day":7,"text":"Cut starts","x":0.08433734939759036,"top":0.6696428571428571,"anchor":"start"},
  {"id":"end","track":"weight","day":83,"text":"Week 12, 5.1 kg down","x":1,"top":0.20535714285714285,"anchor":"end"},
  {"id":"squat","track":"strength","day":56,"text":"New squat record","x":0.6746987951807228,"top":0.13095238095238096,"anchor":"end"},
  {"id":"bench","track":"strength","day":71,"text":"Bench 100 kg x 5, a record","x":0.8554216867469879,"top":0.8988095238095238,"anchor":"end"},
  {"id":"deload","track":"work","day":49,"text":"Deload","x":0.5903614457831325,"top":0.17045454545454544,"anchor":"start"},
];
